# Generated by Django 6.0.2 on 2026-02-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detenteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('grade', models.CharField(choices=[('soldat', 'Soldat'), ('caporal', 'Caporal'), ('sergent', 'Sergent'), ('adjudant', 'Adjudant'), ('lieutenant', 'Lieutenant'), ('capitaine', 'Capitaine'), ('commandant', 'Commandant'), ('colonel', 'Colonel'), ('general', 'Général')], default='lieutenant', max_length=100, verbose_name='Grade')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction')),
                ('image', models.ImageField(blank=True, null=True, upload_to='detenteurs/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Détenteur',
                'verbose_name_plural': 'Détenteurs',
                'db_table': 'core_detenteur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('50/4', '50/4'), ('50/5', '50/5'), ('50/6', '50/6'), ('50/7', '50/7'), ('50/8', '50/8'), ('autre', 'Autre')], default='50/4', max_length=50, verbose_name='Type de document')),
                ('date', models.DateField(verbose_name='Date du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'core_document',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du magasin')),
                ('localisation', models.CharField(max_length=300, verbose_name='Localisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'db_table': 'core_magasin',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('type_materiel', models.CharField(choices=[('radio', 'Radio'), ('telephonique', 'Téléphonique'), ('informatique', 'Informatique'), ('vehicule', 'Véhicule'), ('armement', 'Armement'), ('optique', 'Optique'), ('autre', 'Autre')], default='radio', max_length=100, verbose_name='Type')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('etat', models.CharField(choices=[('service', 'En Service'), ('attente', 'En Attente'), ('approvisionnement', 'Approvisionnement'), ('hors_service', 'Hors Service')], default='service', max_length=50, verbose_name='État')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materiels/', verbose_name='Photo')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('detenteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='core.detenteur', verbose_name='Détenteur')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='core.magasin', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'db_table': 'core_materiel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('perception', 'Perception'), ('reversement', 'Reversement')], default='entree', max_length=50, verbose_name='Type de mouvement')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.document', verbose_name='Document')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.materiel', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'db_table': 'core_mouvement',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['numero_serie'], name='core_materi_numero__ec13cf_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['etat'], name='core_materi_etat_6cf783_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['type_materiel'], name='core_materi_type_ma_51b4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['magasin', 'etat'], name='core_materi_magasin_ebbeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['-created_at'], name='core_materi_created_c57000_idx'),
        ),
    ]
