# Generated by Django 6.0.2 on 2026-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_entree',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AddField(
            model_name='materiel',
            name='date_entree',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
    ]
