# Generated by Django 6.0.1 on 2026-03-13 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_date_entree_to_materiel_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMaterielLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('radar', 'MAT RADAR'), ('uhf', 'MAT RADIO UHF'), ('vhf_groupe', 'MAT RADIO VHF NIVEAU GROUPE'), ('vhf_cie', 'MAT RADIO VHF NIVEAU COMPAGNIE'), ('hf', 'MAT RADIO HF')], max_length=20, unique=True, verbose_name='Code')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie Logistique',
                'verbose_name_plural': 'Catégories Logistiques',
                'db_table': 'core_categorie_logistique',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaireLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation du matériel')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre dans la catégorie')),
                ('qte', models.PositiveIntegerField(default=0, verbose_name='Quantité totale')),
                ('svc', models.PositiveIntegerField(default=0, verbose_name='SVC (En service)')),
                ('mag', models.PositiveIntegerField(default=0, verbose_name='MAG (Magasin)')),
                ('rep', models.PositiveIntegerField(default=0, verbose_name='REP (Réparation)')),
                ('gmi', models.PositiveIntegerField(default=0, verbose_name='GMI')),
                ('gs', models.PositiveIntegerField(default=0, verbose_name='GS')),
                ('gcs', models.PositiveIntegerField(default=0, verbose_name='GCS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.categoriemateriellogistique', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ligne Inventaire Logistique',
                'verbose_name_plural': 'Lignes Inventaire Logistique',
                'db_table': 'core_ligne_inventaire_logistique',
                'ordering': ['categorie__ordre', 'ordre', 'designation'],
            },
        ),
    ]
